// @flow

export const LOAD_WEATHER_SUCCESS = "LOAD_WEATHER_SUCCESS";
export const LOAD_WEATHER_ERRORED = "LOAD_WEATHER_ERRORED";
export const LOAD_WEATHER_LOADING = "LOAD_WEATHER_LOADING";

export const LOAD_WEATHER_LIST_SUCCESS = "LOAD_WEATHER_LIST_SUCCESS";
export const LOAD_WEATHER_LIST_ERRORED = "LOAD_WEATHER_LIST_ERRORED";
export const LOAD_WEATHER_LIST_LOADING = "LOAD_WEATHER_LIST_LOADING";
export const ADD_WEATHER = "ADD_WEATHER";

export default {
  LOAD_WEATHER_SUCCESS,
  LOAD_WEATHER_ERRORED,
  LOAD_WEATHER_LOADING,
  LOAD_WEATHER_LIST_SUCCESS,
  LOAD_WEATHER_LIST_ERRORED,
  LOAD_WEATHER_LIST_LOADING,
  ADD_WEATHER
};
